dropbox:
  consumer_key:     %dropbox_consumer_key%
  consumer_secret:  %dropbox_consumer_secret%

database:
  name:     %database_name%
  user:     %database_user%
  password: %database_password%
  socket:   %database_socket%
